package constants

const DOCINFO_HWPTAG_BEGIN = 0x10

const (
	DOCINFO_HWPTAG_DOCUMENT_PROPERTIES = DOCINFO_HWPTAG_BEGIN + iota
	DOCINFO_HWPTAG_ID_MAPPINGS
	DOCINFO_HWPTAG_BIN_DATA
	DOCINFO_HWPTAG_FACE_NAME
	DOCINFO_HWPTAG_BORDER_FILL
	DOCINFO_HWPTAG_CHAR_SHAPE
	DOCINFO_HWPTAG_TAB_DEF
	DOCINFO_HWPTAG_NUMBERING
	DOCINFO_HWPTAG_BULLET
	DOCINFO_HWPTAG_PARA_SHAPE
	DOCINFO_HWPTAG_STYLE
	DOCINFO_HWPTAG_DOC_DATA
	DOCINFO_HWPTAG_DISTRIBUTE_DOC_DATA
	DOCINFO_HWPTAG_COMPATIBLE_DOCUMENT = DOCINFO_HWPTAG_BEGIN + 1 + iota
	DOCINFO_HWPTAG_LAYOUT_COMPATIBILITY
	DOCINFO_HWPTAG_TRACKCHANGE
	DOCINFO_HWPTAG_MEMO_SHAPE     = DOCINFO_HWPTAG_BEGIN + 60 + iota
	DOCINFO_HWPTAG_FORBIDDEN_CHAR = DOCINFO_HWPTAG_BEGIN + 61 + iota
	DOCINFO_HWPTAG_TRACK_CHANGE   = DOCINFO_HWPTAG_BEGIN + 62 + iota
	DOCINFO_HWPTAG_TRACK_CHANGE_AUTHOR
)
